projeto/produto/urls.py
from django.urls import path

from projeto.produto import views as v

app_name = 'produto'


urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'),
    path('<int:pk>/', v.produto_detail, name='produto_detail'),
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'),
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'),
    path('<int:pk>/json/', v.produto_json, name='produto_json'),
    
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path   

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    path('estoque/', include('projeto.estoque.urls')),
    path('admin/', admin.site.urls),
    path('logout/', LogoutView.as_view(), name='logout'),
]

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
    produto = models.CharField(max_length=100, unique=True)
    estoque = models.IntegerField('estoque atual')
    estoque_minimo = models.PositiveIntegerField('estoque mínimo', default=0)
    data = models.DateField(null=True, blank=True)
    local = models.ForeignKey('Local', on_delete=models.CASCADE)

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }


class Local(models.Model):
    local = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ('local',)

    def __str__(self):
        return self.local

projeto/produto/forms.py
from django import forms

from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

projeto/produto/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, ListView, UpdateView

from .forms import ProdutoForm
from .models import Produto


def produto_list(request):
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    search = request.GET.get('search')
    if search:
        objects = objects.filter(produto__icontains=search)
    context = {'object_list': objects}
    return render(request, template_name, context)


class ProdutoList(ListView):
    model = Produto
    template_name = 'produto_list.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = super(ProdutoList, self).get_queryset()
        search = self.request.GET.get('search')
        if search:
            queryset = queryset.filter(
                Q(produto__icontains=search)
            )
        return queryset


def produto_detail(request, pk):
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)

@login_required
def produto_add(request):
    form = ProdutoForm(request.POST or None)
    template_name = 'produto_form2.html'

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('produto:produto_list'))

    context = {'form': form}
    return render(request, template_name, context)


class ProdutoCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    ''' Retorna o produto, id e estoque. '''
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})


def save_data(data):
    '''
    Salva os dados no banco.
    '''
    aux = []
    for item in data:
        produto = item.get('produto')
        estoque = item.get('estoque')
        estoque_minimo = item.get('estoque_minimo')
        obj = Produto(
            produto=produto,
            estoque=estoque,
            estoque_minimo=estoque_minimo,
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)

projeto/produto/templates/produto_detail.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'produto:produto_list' %}">Voltar</a>

<h1>{{ object }}
  <span class="pull-right">
    <a href="{% url 'produto:produto_edit' object.pk %}">
      <button type="button" class="btn btn-success">
        <span class="fa fa-pencil"></span> Editar
      </button>
    </a>
  </span>
</h1>

<div class="col-sm-6">
  <table class="table table-user-information">
    <tbody>
      
      
      
      <tr>
        <th class="text-right">Estoque</th>
        <td>{{ object.estoque }}</td>
      </tr>
      <tr>
        <th class="text-right">Estoque mínimo</th>
        <td>{{ object.estoque_minimo }}</td>
      </tr>
      <tr>
        <th class="text-right">Local</th>
        <td>{{ object.local }}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

projeto/produto/templates/produto_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<form method="POST" novalidate>
  {% csrf_token %}
  {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif%}">
      <label for="{{ field.id_for_label }}">
        {% if field.field.required %}
          <span class="required">{{ field.label }} </span>
        {% else %}
          {{ field.label }}
        {% endif %}
      </label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
        <span class="text-muted">{{ error }}</span>
      {% endfor %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}

{% block js %}

<script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

projeto/produto/templates/produto_list.html
{% extends "base.html" %}

{% block content %}

{% for message in messages %}
  {% if 'success' in message.tags %}
    <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
  {% else %}
    <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
  {% endif %}
{% endfor %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lista de Produtos
    <span class="pull-right">
      <!-- BOTÃO PARA ADICIONAR PRODUTOS
      <a href="{% url 'produto:produto_add' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>-->
      
    </span>
  </h2>

  {% if object_list %}
    
    <table class="table table-striped">
      <thead>
        <tr>                 
          <th>Produto</th>
          <th class="text-center">Local</th>
          <th class="text-center">Estoque</th>
          <th class="text-center">Estoque mínimo</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>
              <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
            </td>
            <td class="text-center">{{ object.local }}</td>
            <td class="text-center">{{ object.estoque }}</td>
            <td class="text-center">{{ object.estoque_minimo }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% include "includes/pagination.html" %}

{% endblock content %}

{% block js %}

<script>
  // Close alert after 2 seconds
  window.setTimeout(function() {
    $('.alert').fadeTo(500, 0).slideUp(500, function() {
      $(this).remove();
    });
  }, 2000);
</script>

{% endblock js %}